### PR TITLE
changed font

### PR DESCRIPTION
**Pull request by cr4zyafrican**
I changed the font on the about page because it was illegible

### CODE REVIEW

**Comment by KEYS248** [comment]
@cr4zyafrican Why are you only changing the fonts on a single page when all the pages share the same "Press Start 2P" font?

**Comment by cr4zyafrican** [comment]
@KEYS248 because I think only this page should have times new roman since it is content heavy. the rest can have the Press Start 2P font. what do you think?

**Comment by KEYS248** [comment]
Actually yes I agree @cr4zyafrican , not all this h2 and h3 content should be formatted with that font

**Comment by S1MB10T3** [comment]
Yeah h2 and h3 shouldn't be formatted with Press Start 2P. It looks a bit odd...

**Comment by KEYS248** [comment]
lol it didn't change anything. I think this may need to be changed in the CSS with a special class for h2 and h3 that doesn't use Press Start 2P font

**Pull request merged**
